export const PROJECT_DATA_SUCCEEDED = 'PROJECT_DATA.SUCCEEDED';
export const PROJECT_DATA_FAILED = 'PROJECT_DATA.FAILED';
export const PROJECT_DATA_REQUESTED = 'PROJECT_DATA.REQUESTED';

export const MILESTONES_SUCCEEDED = 'MILESTONES.SUCCEEDED';
export const MILESTONES_FAILED = 'MILESTONES.FAILED';
export const MILESTONES_REQUESTED = 'MILESTONES.REQUESTED';

export const TOKEN_ACCEPTED = 'TOKEN.ACCEPTED';

export default {
  PROJECT_DATA_SUCCEEDED,
  PROJECT_DATA_FAILED,
  PROJECT_DATA_REQUESTED,
  MILESTONES_SUCCEEDED,
  MILESTONES_FAILED,
  MILESTONES_REQUESTED,
  TOKEN_ACCEPTED
}